language: python
services:
  - MySQL
  - PostgreSQL
python:
  - 2.7

env:
  - DJANGO="1.4.x" DBENGINE=mysql
  - DJANGO="1.4.x" DBENGINE=pg

  - DJANGO="1.5.x" DBENGINE=mysql
  - DJANGO="1.5.x" DBENGINE=pg

  - DJANGO="1.6.x" DBENGINE=mysql
  - DJANGO="1.6.x" DBENGINE=pg

  - DJANGO="dev" DBENGINE=mysql
  - DJANGO="dev" DBENGINE=pg


install:
  - make install-deps

script:
  - make init-db ci

after_success:
  - coveralls
